spring:
  datasource:
    url: jdbc:postgresql://localhost-prod:5432/techchallenge
    username: "root"
    password: "m@_ssq@HJ7<h(+"
    driver-class-name: org.postgresql.Driver
client:
  mercado-pago:
    user_id: 123456
    pos_id: 123456
    external_store_id: "X"
    external_pos_id: "X"
    notification_url: "http://4.255.73.131:8080/pagamentos/webhook"
    auth_header: "Bearer TEST-X"