name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag fiap-techchallenge01:$(date +%s)

    - uses: docker/login-action@v3.3.0
    - name: Docker Login
      run: docker login -u alecigolini -p ${{ secrets.DOCKER_ACCESS_TOKEN }}
      with:
        username: aleCigolini
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - uses: elgohr/Publish-Docker-Github-Action@v5
    - name: Publish to Registry
      run: docker push alecigolini/fiap-techchallenge01
      with:
        name: aleCigolini/fiap-techchallenge01
        username: aleCigolini
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}